---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - airbyte.airbyte.poc
  resources:
  - airbytesources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airbyte.airbyte.poc
  resources:
  - airbytesources/finalizers
  verbs:
  - update
- apiGroups:
  - airbyte.airbyte.poc
  resources:
  - airbytesources/status
  verbs:
  - get
  - patch
  - update
